### ISSUE TITLE
Sbteclipse should update the referenced libraries even if the whole project does not compile

### ISSUE THREAD

**Issue by amanteaux** [typesafehub/sbteclipse#181]
When an application dependency is updated/deleted (using Build.scala), is it a lot easier to deal with errors in Eclipse than to deal with errors in the Play/sbt terminal.

This issue still exists in the sbteclipse shipped with Play 2.2.1 : I tried to update my project from Play 2.1.2 to Play 2.2.1, sbteclipse detect that Action should now return Promise<SimpleResult> instead of Result :
[error]   return type Result is not compatible with Promise<SimpleResult>
But at the end, sbteclipse fails to do anything :
[error] Could not create Eclipse project files:
[error] Error evaluating task 'dependencyClasspath': error

**Comment by dotta** [comment]
See the [Play documentation](https://www.playframework.com/documentation/2.3.x/IDE) for how to import a project with build errors. Also, note that for a Java Play project you, may need to add an extra setting in your build.sbt because of a bug in Play. See ticket https://github.com/playframework/playframework/issues/3818 for details.

**Comment by benmccann** [comment]
This is because Play is adding `EclipseKeys.preTasks := Seq(compile in Compile)`. You could override Play's setting to change it back to `EclipseKeys.preTasks := Seq()`. The reason they do this is to generate a managed classes directory, which gets added to your Eclipse classpath.

The Play 2.4 docs have some good documentation about this. In Play 2.4 we've made it such that Play no longer does this by default, but you can keep the existing behavior by adding a few lines to your build such that it's clear what's happening and how you can control it.
https://www.playframework.com/documentation/2.4.x/IDE
