### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by benmccann** [typesafehub/sbteclipse#235]
I'd love to use the latest code :-)

**Comment by benmccann** [comment]
@jsuereth could you take a look at this one?

**Comment by benmccann** [comment]
i answered the question about 3.0 bump on the other thread. @jsuereth requested it in one of my PR's. regarding removing 0.12 support it doesn't sound like it's clear we want to do that

@jsuereth think we could get this pushed?

**Comment by er1c** [comment]
From IRC:
`
egp: jsuereth: I still don't understand why the 3.0 major version bump for sbteclipse either
[08:59am] egp: jsuereth: if going to do a major version bump, should try and pull out some of that 0.12 crap
[09:00am] jsuereth: egp, Yeah, maybe a PR of that?
[09:00am] jsuereth: the major version bump was because binary compatibility broke between the 2.x and master
[09:01am] egp: and by binary compat you just mean not generating hte output= anymore?
[09:02am] jsuereth: no, I mean the plugin itself
[09:02am] jsuereth: if someone depends on it,t here was some kind of interface change that would cause NoSuchMethod errors
`
I actually wasn't quite sure what changes occurred in this recent commit that would have broke binary compatibility - unless @jsuereth is just referring to the various changes that have occurred since 2.5.0 was released.

Might be a good opportunity to cleanup the `Build.scala` file if we're going to do a major version bump tho.

**Comment by er1c** [comment]
Tho, now that I look at it, the `Build.scala` isn't as bad as I was recalling.

**Comment by benmccann** [comment]
If you care about bumping SBT when bumping the version, I've created a PR for that here: https://github.com/typesafehub/sbteclipse/pull/236   I don't feel strongly one way or another. I just want there to be a new release since it's been almost a year :-)

**Comment by benmccann** [comment]
ping

**Comment by benmccann** [comment]
Pretty please?

**Comment by er1c** [comment]
I've been trying to get a release since at least october :) (https://github.com/typesafehub/sbteclipse/issues/224)  I tested the current master and it seems to work fine.  We can probably skip the Build.scala crap at this point.

**Comment by dragos** [comment]
Released!

**Comment by benmccann** [comment]
Thank you guys so much!!

**Comment by dragos** [comment]
thank YOU!
