### ISSUE TITLE
Scala 2.11 project contains libraries compiled on 2.10

### ISSUE THREAD

**Issue by boyangli** [typesafehub/sbteclipse#301]
When sbteclipse generates a project on Scala 2.11, it includes libraries compiled with Scala 2.10. This leads to errors in the Eclipse IDE. These libraries have to be manually removed before the project can be compiled. 

Specifically, these libraries are added:

jawn-parser_2.10-0.6.0.jar 
json4s-ast_2.10-3.2.10.jar 
json4s-core_2.10-3.2.10.jar 
json4s-native_2.10-3.2.10.jar 
json4s-support_2.10-0.6.0.jar 
sbinary_2.10-0.4.2.jar

**Comment by sschaef** [comment]
Are these direct dependencies or transitive ones? Can you share your build configuration in order to allow us to reproduce that issue?

**Comment by boyangli** [comment]
These are transitive dependencies. 

My build.sbt:

```
name := "xx" 

organization := "xyz.org"

version := "0.1"

scalaVersion := "2.11.6"

publishMavenStyle := false

publishTo := Some(Resolver.file("file",  new File( "C:\\Users\\me\\.ivy2\\local" )) )

libraryDependencies  ++=  Seq(
    "com.opencsv" % "opencsv" % "3.4",
    "uk.co.caprica" % "vlcj" % "3.8.0",
    "org.slf4j" % "slf4j-api" % "1.7.12"
	)

sbtPlugin := true
```

My project/plugins.sbt:
```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")
```

**Comment by sschaef** [comment]
As far as I know sbt plugins need to run with 2.10, that is why you get these dependencies. I wonder why they even allow users to specify a 2.11 version.

**Comment by boyangli** [comment]
Thanks for the information, @sschaef . Interestingly, the 2.10 dependencies are not needed for running my project. Is there a way to prevent the sbteclipse plugin from adding these dependencies?

**Comment by sschaef** [comment]
Not that I know of. Can't you just run it with 2.10?

**Comment by boyangli** [comment]
I wrote a simple shell script to remove all 2.10 dependencies:

```
#!/bin/sh
sbt eclipse
sed '/\_2\.10/ d' .classpath > temp_cp.txt
mv temp_cp.txt .classpath
```

**Comment by Blaisorblade** [comment]
@boyangli, `scalaVersion := "2.11.6"` is *wrong* for an SBT plugin (since latest SBT builds against Scala 2.10), as also @sschaef suggested. After fixing that, on the latest Eclipse Scala plugin (IIRC 4.1 onwards), you'll then need to make sure Eclipse selects Scala 2.10 (not sure sbteclipse does that on its own).

To all: why does adding an SBT *plugin* impact the base project? The base project and the one in `project` are two separate Scala projects, and SBT plugins in `project/plugins.sbt` should add a dependency to the latter, while `sbteclipse` does *not* generate an Eclipse project for `project` normally. I believe this is the correct behavior even with `sbtPlugin := true`, but `sbteclipse` doesn't seem to implement it — any chance I'm missing something?

**Comment by Blaisorblade** [comment]
> not sure sbteclipse does that on its own

Apparently it doesn't (#287).

**Comment by boyangli** [comment]
I don't think `scalaVersion := "2.11.6"`  is necessarily wrong. Sbt can compile the code using Scala 2.11, while itself runs with Scala 2.10. I tend to think that sbteclipse generates extra dependencies that the project does not need. After removing those, everything works.

**Comment by Blaisorblade** [comment]
But the resulting code must run (hence be compiled) against Scala 2.10. Problems will show up once you try use the resulting plugin in another SBT project.

But I do agree that the `sbteclipse` dependencies don't belong there.

**Comment by boyangli** [comment]
I'm talking about compiling my own project, but compiling sbteclipse.

**Comment by Blaisorblade** [comment]
@boyangli, I'm talking about using your own plugin that you are developing. We all guessed from `sbtPlugin := true` that you're developing your own SBT plugin, but it sounds like that's not your intention. Can you clarify? If that's not it, there might be some other miscommunication happening.

If you're not developing a plugin, can you drop `sbtPlugin := true` from `build.sbt`? That will remove those dependencies, and also many other dependencies on SBT libraries. Those are also compiled against 2.10, only the Eclipse Scala plugin does not detect the mismatch there because of [its heuristic](http://scala-ide.org/docs/current-user-doc/faq/index.html#Scala_IDE_complains_about_‘____is_cross-compiled_with_an_incompatible_version_of_Scala____’).

**Comment by Blaisorblade** [comment]
> To all: why does adding an SBT plugin impact the base project? [...]

That question I retract, it was probably nonsense. Apparently those libraries aren't dependencies of sbteclipse (as I mistakenly assumed), but probably of SBT itself.

**Comment by boyangli** [comment]
I see. I clearly didn't understand the ```sbtPlugin``` option. Thanks so much for pointing that out!

**Comment by Blaisorblade** [comment]
Excellent, happy we're done here! @sschaef, apparently this can indeed be closed!
